export const ADD_ITEM = 'Agregar item'
export const CANCEL = 'Cancelar'
export const ADD = 'Agregar'
export const COUNT_0 = 'Lista vacia'
export const COUNT_1 = '1 ITEM'
export const COUNT_N = ' ITEMS'
export const TITLE_CONTAINER = 'Lista de supermercado'
